
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pc-perso
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    # path: "/mnt/c/Users/MaxenceBierski/Desktop/Projet_web/pv"
    path: "/mnt/f/kube/pv"

