apiVersion: apps/v1
kind: Deployment
metadata:
  name: darkheresyfront
spec:
  selector:
    matchLabels:
      app: darkheresyfront
  replicas: 1
  template:
    metadata:
      labels:
        app: darkheresyfront
    spec:
      containers:
      - name: darkheresyfront
        image: drateil/dhfrontnginx
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "2048mi"
            cpu: "500m"