apiVersion: apps/v1
kind: Deployment
metadata:
  name: darkheresyfront
spec:
  selector:
    matchLabels:
      app: darkheresyfront
  replicas: 1
  template:
    metadata:
      labels:
        app: darkheresyfront
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
      - name: darkheresyfront
        image: drateil/dhfrontnginx
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - mountPath: "/tmp"
          name: task-pv-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: darkheresyback
spec:
  selector:
    matchLabels:
      app: darkheresyback
  template:
    metadata:
      labels:
        app: darkheresyback
    spec:
      containers:
      - name: darkheresyback
        image: drateil/darkheresyback
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3080
