apiVersion: v1
kind: Service
metadata:
  name: darkheresyfront-service
spec:
  selector:
    app: darkheresyfront
  ports:
  - nodePort: 30471
    port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
  
